SELECT 'OLDEST' as TYPE,NAME,BIRTHDAY from worker
WHERE BIRTHDAY IN(
    SELECT MIN(BIRTHDAY) FROM worker
)
UNION
SELECT 'YOUNGEST' as TYPE,NAME,BIRTHDAY from worker
WHERE BIRTHDAY IN(
    SELECT MAX(BIRTHDAY) FROM worker
);